# Generated by Django 3.2 on 2024-03-19 18:36

from django.db import migrations
import django_resized.forms
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_profiles',
            field=django_resized.forms.ResizedImageField(crop=None, default=profiles.models.UserProfile.default_avatar_path, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='profiles/avatars', verbose_name='Аватар'),
        ),
    ]
