# Generated by Django 3.2 on 2024-02-23 09:07

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предметы', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='case',
            name='img_certificates',
            field=django_resized.forms.ResizedImageField(crop=None, default=0, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='case', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='img_certificates',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='items', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название кейса:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='case.case', verbose_name='Из какого кейса:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='chance',
            field=models.FloatField(default=0.0, verbose_name='Шанс выпадения:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество:'),
        ),
    ]
