# Generated by Django 3.2 on 2024-02-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20240223_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img_certificates',
            new_name='img',
        ),
    ]
