# Generated by Django 3.2 on 2024-03-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20240316_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='case',
        ),
        migrations.AddField(
            model_name='item',
            name='cases',
            field=models.ManyToManyField(related_name='items', to='case.Case', verbose_name='Кейсы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='chance',
            field=models.FloatField(default=0.0, verbose_name='Шанс выпадения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
