# Generated by Django 3.2 on 2024-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20240316_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Описание(тег)'),
            preserve_default=False,
        ),
    ]
