# Generated by Django 3.2 on 2024-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='useritem',
            name='conclusion',
            field=models.BooleanField(default=False),
        ),
    ]
