# Generated by Django 3.2 on 2024-03-17 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20240317_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
