# Generated by Django 3.2 on 2024-03-17 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0013_auto_20240317_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('keys_count', models.IntegerField(verbose_name='Количество ключей')),
                ('is_single_use', models.BooleanField(default=True, verbose_name='Одноразовый промокод')),
                ('activations_left', models.IntegerField(default=1, verbose_name='Количество активаций')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Ключ', 'verbose_name_plural': 'Ключи'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='keys_count',
            field=models.IntegerField(default=0, verbose_name='Количество ключей'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
