# Generated by Django 3.2 on 2024-03-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_auto_20240319_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='useritem',
            options={'verbose_name': 'Live лента'},
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
