# Generated by Django 3.2 on 2024-03-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_auto_20240319_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useritem',
            options={'verbose_name': 'Live лента', 'verbose_name_plural': 'Live лента'},
        ),
    ]
