# Generated by Django 3.2 on 2024-03-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_alter_useritem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='case.case', verbose_name='Кейс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useritem',
            name='client_seed',
            field=models.CharField(default=1, max_length=255, verbose_name='Client Seed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useritem',
            name='nonce',
            field=models.IntegerField(default=0, verbose_name='Nonce'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='server_seed',
            field=models.CharField(default=1, max_length=255, verbose_name='Server Seed'),
            preserve_default=False,
        ),
    ]
